export const MAKE_TILE_EDITABLE = 'MAKE_TILE_EDITABLE'
export const TOGGLE_GAME_TYPE = 'TOGGLE_GAME_TYPE'
export const UPDATE_RACK = 'UPDATE_RACK'
export const CHANGE_COORDINATE_VALUE = 'CHANGE_COORDINATE_VALUE'