// Board / Tile
export const CHANGE_COORDINATE_VALUE = 'CHANGE_COORDINATE_VALUE'
export const PLAY_WORD = 'PLAY_WORD'

// Tile
export const SET_MOVE_DIRECTION = 'SET_MOVE_DIRECTION'
export const MAKE_TILE_EDITABLE = 'MAKE_TILE_EDITABLE'

// Rack
export const UPDATE_RACK = 'UPDATE_RACK'
export const REMOVE_PLAYED_LETTERS_FROM_RACK = 'REMOVE_PLAYED_LETTERS_FROM_RACK'

// Wordlist
export const HIGHLIGHT_SUGGESTED_WORD = 'HIGHLIGHT_SUGGESTED_WORD'
export const RESET_SUGGESTED_WORDS = 'RESET_SUGGESTED_WORDS'

// Websockets
export const SENT_TABLE_DATA = 'SENT_TABLE_DATA'
export const RECEIVED_SUGGESTED_WORDS = 'RECEIVED_SUGGESTED_WORDS'

// Gametype 
export const TOGGLE_GAME_TYPE = 'TOGGLE_GAME_TYPE'